### ISSUE TITLE
File List by Declaration

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-decl#19]
**Methods:**
- [ ] toFiles
- [ ] toFilesSync

The method should get files by declaration.

```
.
├── common.blocks/
│   └── block/
│       ├── block.css/
│       └── block.js/
└── bemconf.json
```

``` js
var toFiles = require('bem-decl').toFilesSync,
    decl = [
        { block: 'block' }
    ];

toFiles(decl); 
// [
//     'common.blocks/block/block.css',
//     'common.blocks/block/block.js'
// ]
```

**Comment by tadatuta** [comment]
1. why it's a method of `bem-decl`?
2. what's the difference from scaner/walker?
3. how it knows about `levels` and `levelSchema`?
4. what are use cases for it?

**Comment by blond** [comment]
> why it's a method of bem-decl

this method work with declaration

> what's the difference from scaner/walker

Scanner talks about all the entities found in levels.

This method get only files from BEMDECL (translate BEMDECL to Array<File>).

> how it knows about levels and levelSchema?

In this example, the information is taken from the `bemconf.json` file.

> what are use cases for it

With the declaration to get a list of files for further processing.

**Comment by blond** [comment]
@tadatuta, In what package you would place this logic?

**Comment by zxqfox** [comment]
Agreed with @tadatuta. Strange to have it here.

I'd rather place it in `bem-levels` or something that know about fs structure (bem-fs?).

**Comment by blond** [comment]
@tadatuta, @zxqfox could you write an example that solves this problem with `bem-levels`, `bem-walk` or `bem-fs`?

**Comment by tadatuta** [comment]
I've already wrote an example for `bem-walk`:
1. it should be possible to subscribe for specific events
2. it is possible to filter the result right away

so for me it's just the subset of what `bem-walk` is all about.

**Comment by blond** [comment]
@tadatuta If you have a declaration and name of technology you can get a list of files without looking at the file system.

**Example**

BEMDECL:

```js
[
    { block: 'block-1' },
    { block: 'block-2' }
]
```

* levels — `['common.blocks', 'desktop.blocks']`
* naming — `{ elem: '__', mod: '_' }`
* level scheme — `nested`
* tech — `css`

Files:

```js
[
    'common.blocks/block/block-1.css',
    'common.blocks/block/block-2.css',
    'desktop.blocks/block/block-1.css',
    'desktop.blocks/block/block-2.css'
]
```

**Comment by zxqfox** [comment]
`bem-walk` is just a data provided for FS with several schemes. It provides a simple event-based interface to spam data and bem-entities for ya. It not about 

`bem-walk` for me can be a part of `bem-fs` (which also have some writer). Moreover with this abstraction we can merge bem-entities from different data-storages (not only files).
E.g. we can merge dynamic blocks (made just now in runtime) and "static" (from `bem-core` or other libraries) with just one `bem-storage` module.

`bem-levels` should contains scheme, should know about configurations for levels (e.g. type, path, schema according to type, etc.), and it's just helper to work with level.

So the pie for me is:
```
       bem-storage      + {levels[level1, level2, level3]}
       /    |    \
     fs    db?    web?
   /    \
walk   writer
```

`fs` and `db` here just adapters to data. Nothing more.

In particular case when we working with usual project placed on `fs` we just using one adapter (`bem-walk` + `native fs` or just `bem-fs`) and doesn't think much about how it works.

For web we can make virtual `fs` provider in memory that will provide the same public API as others — this will give us possibility to make any block storages/libraries.

Moreover with that architecture we can generate even randomized blocks.

So I'm not sure why you stuck with that here. `bem-decl` is another level of abstraction and shouldn't know anything about files. Only about how to read, write (I mean parse and serialize), merge, subtract, etc `bem-entities`.

**Comment by tadatuta** [comment]
@blond ok, you can, but what for? I can imagine just one case — for `create` command. But I'd rather put this logic right there as it's useless for anything ease.

@zxqfox it'd be great if you also provide some real-life examples where such multilevel abstractions were needed for you. the more levels we've got the harder it's the harder to master the stack and each level also affects performance and makes support more complicated. `entities must not be multiplied beyond necessity` ;)

**Comment by zxqfox** [comment]
Skissors should be sharp!

**Comment by zxqfox** [comment]
@tadatuta I want to run builds in browser. I couldn't use these modules if you will use node's `fs` module. And modularity will fail.

**Comment by tadatuta** [comment]
@zxqfox what is a real use case for build in a browser?

**Comment by zxqfox** [comment]
No real cases today. Tomorrow only. ;-)

Are you trolling me or what?

**Comment by tadatuta** [comment]
@zxqfox nope, I'm just trying to understand why should we create 5 packages instead of one. There's no such necessity in my own experience, so I ask for your's. If you don't have it either, I'd better focus on some real cases and postpone everything else.
But if such cases really exist and are useful for a lot of people, we can decide to do it the way you described.

**Comment by zxqfox** [comment]
@tadatuta What is the real case where we need to make independent blocks if we can right one html/css/js file? Each level of abstraction should have their set of responsibilities. If some parts will know too much — it will ruin modularity. E.g. http://en.wikipedia.org/wiki/God_object.

If you'll make some parts of these modular build system too dependent of environment — you'll get the same problem after a year or 2. Why not to make this good from scratch when we can do this for free?

**Comment by zxqfox** [comment]
@tadatuta Nope, you don't. You just need to think twice about Public APIs of modules you maintain or write, and about it's level of responsibility.

**Comment by blond** [comment]
It is not the task of this package.
