### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Yeti-or** [bem-sdk/bem-decl#25]
Let's use @bem/decl ?

**Comment by zxqfox** [comment]
Let's use anything
:+1: for @bem

**Comment by Yeti-or** [comment]
@blond what do u think? do u still like idea of @bem namespace?

**Comment by blond** [comment]
I think need to refuse `@bem` namespace and publish this package with `bem-decl` name.

**Comment by vithar** [comment]
@blond Yes

**Comment by zxqfox** [comment]
Actually, there are more important issues over here ;-)

**Comment by blond** [comment]
done: `bem-decl@0.1.0`.
