### ISSUE TITLE
Read File

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-decl#5]
**Methods:**
- [ ] `read(filename, callback)`
- [ ] `readSync(filename)`

The method should determine the format of the file content.

**BEMDECL 1.0**

``` js
exports.blocks = [
    { name: 'block' }
];
```

or

``` js
exports.version = '1.0';
exports.decl = [
    { name: 'block' }
];
```

**BEMDECL 2.0**

``` js
exports.version = '2.0';
exports.decl = [
    { block: 'block' }
];
```

**BEMDECL next**

``` js
exports.version = 'next';
exports.decl = [
    { block: 'block' }
];
```

The method should translate any format to [normalized](https://github.com/bem/bem-decl/issues/15) **BEMDECL 2.0**.

``` js
var read = require('bem-decl').readSync;

// bemdecl-1.0.js
// exports.blocks = [
//     { name: 'block' }
// ];

read('bemdecl-1.0.js'); // [{ block: 'block' }]
```

**Comment by zxqfox** [comment]
Are you sure that you need that in `bem-decl`? Why not to make this as `DeclCollection` without any knowings about `fs`?

**Comment by blond** [comment]
There is a logic which defines the format of the file content. Easy to store the code in this tool instead of writing each time.

I don't see anything wrong with that, if the fs-logic will be in the additional fields of namespace:
* read(filename)
* write(filename, decl)

**Comment by zxqfox** [comment]
Mm. That's a little bit strange, because if I want to use it in browser I'll get some troubles.

Can we split core functionality and this reader/write to different files, and use version with `fs` just on purpose?

**Comment by blond** [comment]
> Can we split core functionality and this reader/write to different files, and use version with fs just on purpose?

Yes, it will! ;)

**Comment by zxqfox** [comment]
See also #33

**Comment by blond** [comment]
Fixed in https://github.com/bem-sdk/bem-decl/pull/62
